// Dynamic greetings for Heidi's dashboard — parrot-themed, time-aware,
// with entrepreneur quotes, scaling tips, and pastry business advice.
// All in Spanish with parrot personality 🦜

// Morning (before noon) — energy, starting the day, entrepreneur mindset
const morningGreetings = [
  // ── Parrot personality ──
  "¡Buenos días, Heidi! 🦜",
  "¡Arriba las plumas, Heidi!",
  "¡SQUAWK! Buen día, Heidi 🦜",
  "¡A hornear se ha dicho, Heidi!",
  "Loro madrugador, Heidi 🦜",
  "¡Plumas listas! Buenos días, Heidi",
  "¡Alas arriba, que ya amaneció! 🦜",
  "El horno ya calienta, Heidi 🦜",
  "¡Buenos días, reina lorita! 🦜",
  "¡Hoy se hornea bonito, Heidi!",
  "¿Lista para el primer vuelo? 🦜",
  "¡Café y galletas! Buenos días 🦜",
  "Primer vuelo del día, Heidi 🦜",
  "¡Despierta, cotorrita linda! 🦜",
  "¡Mañana de galletitas, Heidi!",
  "¡Sol, plumas y horno! Buenos días 🦜",
  "¡Qué bonita mañana, Heidi!",
  "Hoy va a ser un gran día, Heidi 🦜",
  "¡Buenos días desde la percha! 🦜",
  "¡Sacude las plumas y al horno! 🦜",
  "¡La panadería abre tempranito! 🦜",
  "¡A darle con todo esta mañana! 🦜",
  "¡El sol salió y el loro también! 🦜",
  // ── Entrepreneur motivation ──
  "¡Los sueños se hornean temprano! 🦜",
  "La constancia hace imperios, Heidi 🦜",
  "Tú y munchis van a volar alto 🦜",
  "Hoy munchis crece un poquito más 🦜",
  "Las mejores marcas empezaron en una cocina 🦜",
  "Cada mañana es una nueva oportunidad 🦜",
  "¡El mundo necesita más munchis! 🦜",
  "Tu receta, tu negocio, tu imperio 🦜",
  "Hoy alguien va a probar munchis por primera vez 🦜",
  "Las grandes panaderías empezaron con un solo horno 🦜",
  // ── Entrepreneur quotes ──
  "Sara Blakely empezó con $5,000… tú tienes un horno 🦜",
  "Walt Disney fue rechazado 302 veces. ¡Tú ya vendes! 🦜",
  "\"El secreto es empezar\" — Mark Twain 🦜",
  "Estée Lauder empezó vendiendo cremas puerta a puerta 🦜",
  "Mrs. Fields empezó con una receta y un sueño, como tú 🦜",
  "Debbi Fields: le dijeron que nadie compraría galletas 🦜",
  "Christina Tosi abrió Milk Bar en un local diminuto 🦜",
  "Magnolia Bakery empezó en un sótano de NYC 🦜",
  "Joanne Chang dejó Harvard para abrir Flour Bakery 🦜",
  "Duff Goldman empezó horneando en su casa para amigos 🦜",
  "Dominique Ansel inventó el cronut en una cocina chiquita 🦜",
  "\"Empieza donde estás, usa lo que tienes\" — Arthur Ashe 🦜",
  "\"Cada experto fue alguna vez principiante\" 🦜",
  "\"La mejor hora para empezar fue ayer, la segunda es hoy\" 🦜",
  "\"El 80% del éxito es simplemente presentarse\" — Woody Allen 🦜",
  "\"La acción es la llave del éxito\" — Picasso 🦜",
  "\"Si crees que puedes, ya estás a medio camino\" — Roosevelt 🦜",
  "Henry Ford: \"tanto si crees que puedes como si no, tienes razón\" 🦜",
  "\"Deja de hablar y empieza a hacer\" — Walt Disney 🦜",
  "\"Lo que sea que la mente pueda concebir, lo puede lograr\" — Napoleon Hill 🦜",
  "Branson: \"un gran negocio empieza pequeño\" 🦜",
  "\"No he fracasado, encontré 10,000 formas que no funcionan\" — Edison 🦜",
  "\"Solo hay que acertar una vez\" — Drew Houston, Dropbox 🦜",
  "\"Persigue la visión, no el dinero\" — Tony Hsieh 🦜",
  "Debbi Fields: \"mi trabajo es vender alegría, no galletas\" 🦜",
  "Christina Tosi: \"ser humilde y atreverte van de la mano\" 🦜",
  "Dominique Ansel: \"la creatividad requiere trabajo, prueba y error\" 🦜",
  "Joanne Chang: \"las cosas simples, bien hechas, son las mejores\" 🦜",
  "Sophia Amoruso: \"no vas a destacar si no piensas en grande\" 🦜",
  "\"Arriesga más de lo que otros creen seguro\" — Howard Schultz 🦜",
  "Starbucks empezó vendiendo solo granos de café 🦜",
  "\"Haz lo que amas y no trabajarás ni un día\" 🦜",
  "Joanne Chang dejó Harvard y encontró su pasión horneando 🦜",
  "Joanne Chang cambió las matemáticas por harina 🦜",
  "Ser ingeniera de alimentos es tu superpoder secreto, Heidi 🦜",
  "Tú entiendes la ciencia detrás del sabor, eso es tu ventaja 🦜",
  "De Bimbo a tu propia panadería… ese es el vuelo, Heidi 🦜",
  "La industria te dio el conocimiento, munchis te da la libertad 🦜",
  "Cada drop te acerca más a tu propia panadería 🦜",
  "Un día vas a abrir las puertas de tu bakery, Heidi 🦜",
  "Joanne Chang dijo: \"quería mi propia plataforma\"… tú ya la tienes 🦜",
  "Tu título de ingeniera + tu pasión = combinación invencible 🦜",
  // ── Scaling tips ──
  "Tip: fotografía cada creación, tu feed es tu vitrina 🦜",
  "Tip: un cliente feliz te trae tres más 🦜",
  "Tip: la consistencia en el sabor crea lealtad 🦜",
  "Tip: empaca bonito, la presentación vende 🦜",
  "Tip: anota qué sabores piden más, los datos son oro 🦜",
  "Tip: planea tu semana de hornear los domingos 🦜",
  "Tip: haz tu mise en place antes de empezar 🦜",
  "Tip: pesa los ingredientes, no uses tazas 🦜",
  "Tip: hornea en lotes para ser más eficiente 🦜",
  "Tip: ten tu receta estrella siempre lista 🦜",
  "Tip: la luz natural hace las mejores fotos de comida 🦜",
  "Tip: crea un hashtag propio para munchis 🦜",
  "Tip: ofrece muestras gratis a influencers locales 🦜",
  "Tip: un logo consistente construye marca 🦜",
  "Tip: responde mensajes rápido, la velocidad vende 🦜",
  "Tip: actualiza tu perfil de Google Business 🦜",
  "Tip: el 80% contenido útil, 20% promoción directa 🦜",
  "Tip: un menú chico pero perfecto vence a uno enorme 🦜",
  "Tip: publica consistentemente, no necesitas que sea perfecto 🦜",
  "Tip: compra ingredientes al mayoreo para mejorar márgenes 🦜",
];

// Afternoon (noon–8pm) — keep going, hustle, growth mindset
const afternoonGreetings = [
  // ── Parrot personality ──
  "¡Buenas tardes, Heidi! 🦜",
  "¡Qué tal la tarde, Heidi! 🦜",
  "¡Seguimos volando, Heidi!",
  "Tarde de hornear, Heidi 🦜",
  "¡Lorita trabajadora! Buenas tardes",
  "¡Plumas al viento esta tarde! 🦜",
  "¿Cómo va la tarde, Heidi? 🦜",
  "¡Media tarde y seguimos al pie! 🦜",
  "¡Hola de nuevo, Heidi! 🦜",
  "¡Siesta no, galletas sí, Heidi! 🦜",
  "¿Más pedidos? ¡Vamos, Heidi! 🦜",
  "¡Tarde productiva, Heidi! 🦜",
  "El horno no para esta tarde 🦜",
  "¡La tarde es joven, Heidi!",
  "¡Loro feliz, tarde feliz! 🦜",
  "¿Un snack? Te lo mereces, Heidi 🦜",
  "¡Buenas tardes, jefa lorita! 🦜",
  "Todavía queda vuelo, Heidi 🦜",
  "¡El loro aplaude tu esfuerzo! 🦜",
  "¡Huele a galletas esta tarde! 🦜",
  "¡Dale que la tarde rinde, Heidi! 🦜",
  "¡Tarde con sabor a munchis! 🦜",
  // ── Entrepreneur quotes — afternoon push ──
  "Los grandes negocios empiezan así 🦜",
  "¡Cada pedido es un paso más! 🦜",
  "Munchis es tu bebé, y está creciendo 🦜",
  "La magia está en la constancia 🦜",
  "¡Qué orgullo lo que estás creando! 🦜",
  "Coco Chanel empezó con un sombrerito… tú con una galleta 🦜",
  "No necesitas ser grande para empezar, Heidi 🦜",
  "Hoy un drop, mañana una franquicia 🦜",
  "Cada cliente satisfecho es publicidad gratis 🦜",
  "Tu competencia no tiene tu sazón, Heidi 🦜",
  "El éxito es la suma de pequeños esfuerzos diarios 🦜",
  "Oprah empezó desde cero… tú ya tienes munchis 🦜",
  "\"Nunca te rindas, los milagros toman tiempo\" — Oprah 🦜",
  "Gary Vee dice: la paciencia es la estrategia #1 🦜",
  "\"Tu marca es lo que dicen de ti cuando no estás\" — Bezos 🦜",
  "Buffett invierte en lo que entiende… tú entiendes postres 🦜",
  "\"Haz algo tan bien que quieran volver\" — Walt Disney 🦜",
  "Howard Schultz: Starbucks empezó vendiendo solo granos 🦜",
  "\"El producto es rey\" — Steve Jobs 🦜",
  "Branson: \"fui terrible estudiante, buen emprendedor\" 🦜",
  "\"Si no construyes tu sueño, otro te contratará para el suyo\" 🦜",
  "Rachael Ray empezó dando clases de cocina de $30 🦜",
  "\"La creatividad es inteligencia divirtiéndose\" — Einstein 🦜",
  "Mark Cuban: \"no se trata de dinero, se trata de esfuerzo\" 🦜",
  "\"Ponte nerviosa y hazlo de todos modos\" — Sheryl Sandberg 🦜",
  "Buddy Valastro heredó la panadería a los 17 y la hizo crecer 🦜",
  "Martha Stewart empezó haciendo catering desde su casa 🦜",
  "\"Sé tan buena que no puedan ignorarte\" — Steve Martin 🦜",
  "Ina Garten compró una tienda de comida sin saber cocinar 🦜",
  "\"El riesgo más grande es no tomar ninguno\" — Zuckerberg 🦜",
  "Lady M Cakes empezó con un solo pastel de crepes 🦜",
  "\"Trabaja duro en silencio, deja que el éxito haga ruido\" 🦜",
  // New quotes from research
  "\"Si algo importa lo suficiente, hazlo aunque las probabilidades estén en tu contra\" — Musk 🦜",
  "\"Si no estás fallando, no estás innovando\" — Elon Musk 🦜",
  "\"Innovar es lo que distingue a un líder\" — Steve Jobs 🦜",
  "\"Sabía que no me arrepentiría de intentarlo\" — Jeff Bezos 🦜",
  "\"Trabaja duro, diviértete, haz historia\" — Jeff Bezos 🦜",
  "\"Toma 20 años construir reputación y 5 min perderla\" — Buffett 🦜",
  "\"Precio es lo que pagas, valor es lo que recibes\" — Buffett 🦜",
  "\"Las oportunidades son como buses, siempre viene otro\" — Branson 🦜",
  "Coco Chanel: \"el éxito lo logran los que no le temen al fracaso\" 🦜",
  "\"No te intimides por lo que no sabes, es tu mayor fuerza\" — Sara Blakely 🦜",
  "\"Equivocarse es importante, lo peor es ser olvidable\" — Blakely 🦜",
  "Sheryl Sandberg: \"¿qué harías si no tuvieras miedo?\" 🦜",
  "\"Si te ofrecen un asiento en un cohete, ¡súbete!\" — Sandberg 🦜",
  "Whitney Wolfe Herd fundó Bumble a los 25 años 🦜",
  "\"Las oportunidades no esperan, créalas\" — Whitney Wolfe Herd 🦜",
  "\"Nunca limites tus retos, reta tus límites\" — Cher Wang 🦜",
  "\"Asume siempre que tienes algo que aprender\" — Indra Nooyi 🦜",
  "Debbi Fields: \"'suficientemente bueno' nunca lo es\" 🦜",
  "Christina Tosi: \"romper convenciones enciende almas e imaginación\" 🦜",
  "Dominique Ansel: \"no dejes que una creación mate tu creatividad\" 🦜",
  "Dominique Ansel: \"crecer está bien, pero con consciencia\" 🦜",
  "Joanne Chang: \"quería tener mi propia plataforma\" 🦜",
  "\"El fracaso es solo práctica para el éxito\" 🦜",
  "Buddy Valastro: \"buen ingrediente + buena actitud = maravillas\" 🦜",
  "\"Solo haz cosas que te apasionen y el dinero viene solo\" — Zuckerberg 🦜",
  "\"Cada día estoy en la lucha\" — Daymond John 🦜",
  "\"No es sobre ideas, es sobre hacerlas realidad\" — Scott Belsky 🦜",
  "\"Una visión sin ejecución es una alucinación\" — Steve Case 🦜",
  "\"Tus clientes insatisfechos son tu mayor aprendizaje\" — Bill Gates 🦜",
  "\"Si miré más lejos fue por estar sobre hombros de gigantes\" — Newton 🦜",
  "\"La única forma de hacer un gran trabajo es amar lo que haces\" — Jobs 🦜",
  "\"Los éxitos de la noche a la mañana tomaron mucho tiempo\" — Jobs 🦜",
  "Madam C.J. Walker: primera millonaria self-made de EEUU 🦜",
  "Sophia Amoruso empezó vendiendo ropa usada en eBay 🦜",
  "Joanne Chang cambió Harvard por un horno… y creó Flour Bakery 🦜",
  "Joanne Chang: \"un año sabático me mostró mi verdadera pasión\" 🦜",
  "Tú ya sabes la ciencia del sabor, Heidi… eso nadie te lo quita 🦜",
  "Ingeniera de alimentos con sueño de bakery = receta ganadora 🦜",
  "Bimbo te enseñó escala… munchis te enseña alma 🦜",
  "Cada receta que perfeccionas es un paso a tu panadería 🦜",
  "Munchis hoy, tu bakery mañana… el vuelo ya empezó 🦜",
  // ── Scaling tips — afternoon action ──
  "Tip: pide reseñas a tus clientes felices 🦜",
  "Tip: ofrece un sabor edición limitada para crear urgencia 🦜",
  "Tip: las stories venden más que los posts 🦜",
  "Tip: busca un café local que quiera vender munchis 🦜",
  "Tip: congela masa lista para hornear en picos de demanda 🦜",
  "Tip: arma combos, la gente ama sentir que ahorra 🦜",
  "Tip: manda una notita escrita a mano con cada pedido 🦜",
  "Tip: repite lo que funciona antes de inventar algo nuevo 🦜",
  "Tip: haz pre-venta para saber cuánto hornear 🦜",
  "Tip: el packaging es tu primer punto de contacto 🦜",
  "Tip: crea una lista de espera cuando se agote un drop 🦜",
  "Tip: publica el \"detrás de cámaras\" de hornear 🦜",
  "Tip: ofrece delivery en zonas cercanas para empezar 🦜",
  "Tip: pon tu precio justo, no regales tu trabajo 🦜",
  "Tip: calcula tu costo por unidad incluyendo tu tiempo 🦜",
  "Tip: responde cada DM, cada mensaje es una venta potencial 🦜",
  "Tip: crea un sabor de temporada para cada mes 🦜",
  "Tip: regala una galleta extra, la generosidad fideliza 🦜",
  "Tip: graba un reel del horno al plato, la gente lo ama 🦜",
  "Tip: alianzas con cafeterías = volumen constante de wholesale 🦜",
  "Tip: en apps de delivery, optimiza tu menú para viaje 🦜",
  "Tip: catering para bodas, cumples y oficinas = ingreso grande 🦜",
  "Tip: una caja de suscripción mensual = ingreso recurrente 🦜",
  "Tip: toma pedidos dom-mié, hornea y entrega jue-sáb 🦜",
  "Tip: usa 3 niveles de precio: entrada, core y premium 🦜",
  "Tip: el costo de empaque debe ser <10% del precio final 🦜",
  "Tip: no compitas en precio, compite en calidad y experiencia 🦜",
  "Tip: un menú rotativo por temporada mantiene el interés 🦜",
  "Tip: haz lives horneando, la gente ama ver el proceso 🦜",
  "Tip: colabora con influencers de comida locales 🦜",
  "Tip: Google Business Profile es gratis y te trae clientes 🦜",
];

// Evening (8pm–10pm) — reflecting, proud of the day, visionary vibes
const eveningGreetings = [
  // ── Parrot personality ──
  "¡Buenas noches, Heidi! 🦜",
  "Atardecer con plumas, Heidi 🦜",
  "¿Revisando el día, Heidi? 🦜",
  "El loro dice: buen trabajo hoy 🦜",
  "¿Último vistazo del día, Heidi? 🦜",
  "¡Qué buen día fue, Heidi! 🦜",
  "Hora de guardar el delantal 🦜",
  "¡Noche tranquila, Heidi! 🦜",
  "¡Misión cumplida hoy, Heidi! 🦜",
  "Nochecita rica, Heidi 🦜",
  "¡Buenas noches desde la percha! 🦜",
  "Hoy fue un buen vuelo, Heidi 🦜",
  "¡Lo hiciste genial hoy, Heidi! 🦜",
  "¡Plumas relajadas, Heidi! 🦜",
  "El nido te espera, Heidi 🦜",
  "¡Noche de estrellas y plumas! 🦜",
  "Cierra el día con una sonrisa 🦜",
  // ── Entrepreneur reflection — evening wisdom ──
  "Munchis crece gracias a ti 🦜",
  "¡Qué bonito lo que estás construyendo! 🦜",
  "El éxito se hornea con paciencia 🦜",
  "Mañana será aún mejor, Heidi 🦜",
  "Un pasito más cerca del sueño 🦜",
  "Todo esfuerzo vale la pena 🦜",
  "Roma no se construyó en un día, ni munchis tampoco 🦜",
  "Las mejores ideas nacen de la pasión, Heidi 🦜",
  "Hoy sembraste, mañana cosechas 🦜",
  "Tu marca ya tiene personalidad, eso no se compra 🦜",
  "Cada noche eres más empresaria que ayer 🦜",
  "Jeff Bezos empezó en un garaje… tú en tu cocina 🦜",
  "Steve Jobs decía: stay hungry… tú ya lo logras con munchis 🦜",
  "\"La perseverancia no es carrera larga, son muchas carreras cortas\" 🦜",
  "Elon Musk durmió en su oficina… tú al menos tienes galletas 🦜",
  "\"El éxito no es definitivo, el fracaso no es fatal\" — Churchill 🦜",
  "Sara Blakely dice: \"falla rápido y aprende más rápido\" 🦜",
  "\"No se trata de ideas, se trata de hacer que pasen\" — Scott Belsky 🦜",
  "Madam C.J. Walker fue la primera millonaria self-made de EEUU 🦜",
  "\"Tu tiempo es limitado, no lo vivas para otros\" — Steve Jobs 🦜",
  "Indra Nooyi: de India a CEO de PepsiCo con disciplina y visión 🦜",
  "\"Los obstáculos son esas cosas que ves cuando pierdes el foco\" 🦜",
  "\"Primero te ignoran, luego se ríen, luego pelean, luego ganas\" 🦜",
  "Sophia Amoruso empezó vendiendo ropa usada en eBay 🦜",
  "\"No busques clientes para tu producto, busca productos para tus clientes\" 🦜",
  "Whitney Wolfe Herd fundó Bumble a los 25 años 🦜",
  "\"La mejor venganza es un éxito masivo\" — Frank Sinatra 🦜",
  // New evening quotes from research
  "\"El miedo no es la ausencia de valor, es dominarlo\" — Arianna Huffington 🦜",
  "\"El éxito no es escalar, es qué tan plena es la vida que creas\" — Huffington 🦜",
  "\"Mientras más nos ayudemos entre mujeres, más nos ayudamos\" — Sandberg 🦜",
  "\"El éxito es pasión, y no hay pasión sin inspiración\" — Sophia Amoruso 🦜",
  "\"La distancia entre #1 y #2 siempre es constante\" — Indra Nooyi 🦜",
  "\"No subestimes el poder de tus propias ideas\" — Whitney Wolfe Herd 🦜",
  "\"Ser valiente es ser la única que sabe que tiene miedo\" — Wolfe Herd 🦜",
  "Debbi Fields: \"nunca he vendido galletas, vendo felicidad\" 🦜",
  "Christina Tosi: \"soy obsesiva, dame una lista y no paro hasta acabarla\" 🦜",
  "Dominique Ansel: \"crear y compartir buena comida es un privilegio\" 🦜",
  "Joanne Chang: \"deberías sentirte más feliz al irte que al llegar\" 🦜",
  "Joanne Chang: \"lo más importante es saber manejar personas\" 🦜",
  "\"Toma 20 años construir reputación y 5 minutos arruinarla\" — Buffett 🦜",
  "\"Las oportunidades son como buses, siempre viene otro\" — Branson 🦜",
  "\"Trabaja como si alguien trabajara 24h para quitarte el puesto\" — Cuban 🦜",
  "\"Los líderes trabajan para su equipo, no al revés\" — Gary Vee 🦜",
  "\"Los mejores líderes son los más conscientes de sí mismos\" — Gary Vee 🦜",
  "\"Asume intención positiva y todo cambia\" — Indra Nooyi 🦜",
  "\"Nunca dejes de aprender\" — Indra Nooyi 🦜",
  "Ree Drummond empezó un blog de cocina… hoy tiene un imperio 🦜",
  "Joanne Chang: Harvard le dio disciplina, la cocina propósito 🦜",
  "Tu formación como ingeniera es la base de tu imperio, Heidi 🦜",
  "Pocos tienen tu combo: ciencia + creatividad + pasión 🦜",
  "Cada día en Bimbo es aprendizaje que llevarás a tu bakery 🦜",
  "De Harvard a la harina… el salto de Joanne inspiró el tuyo 🦜",
  "Tu panadería ya existe en tu mente… munchis la construye 🦜",
  // ── Scaling tips — evening planning ──
  "Tip: revisa qué drop vendió más y repítelo 🦜",
  "Tip: planea el menú de la semana esta noche 🦜",
  "Tip: piensa en un packaging que la gente quiera postear 🦜",
  "Tip: un programa de cliente frecuente fideliza 🦜",
  "Tip: escribe lo que aprendiste hoy del negocio 🦜",
  "Tip: investiga ferias locales para vender en persona 🦜",
  "Tip: el boca a boca es tu mejor marketing 🦜",
  "Tip: piensa en colaboraciones con otros emprendedores 🦜",
  "Tip: define tu cliente ideal y habla directo a ella 🦜",
  "Tip: separa las finanzas de munchis de las personales 🦜",
  "Tip: reinvierte un % de cada venta en mejorar el negocio 🦜",
  "Tip: busca mentores, alguien ya pasó por donde tú estás 🦜",
  "Tip: crea una lista de correos de tus clientes 🦜",
  "Tip: piensa en catering para eventos y oficinas 🦜",
  "Tip: documenta tus recetas con gramos exactos 🦜",
  "Tip: analiza qué días vendes más y enfoca ahí 🦜",
  "Tip: el empaque ecológico atrae clientes conscientes 🦜",
  "Tip: establece un día fijo de drop, la rutina crea hábito 🦜",
  "Tip: empieza a delegar cuando ya no puedas sola 🦜",
  "Tip: vende la experiencia, no solo el producto 🦜",
  "Tip: ten tu e-commerce listo para envíos nacionales 🦜",
  "Tip: pricing keystone: duplica el costo total como regla base 🦜",
  "Tip: cada nuevo sabor suma complejidad, simplifica sin miedo 🦜",
  "Tip: domina 1-2 redes sociales antes de expandir a más 🦜",
  "Tip: Bradford Bakery empezó con $500 y hoy factura $72K/año 🦜",
];

// Late night (10pm+) — rest reminders, dreaming big, gentle wisdom
const lateNightGreetings = [
  // ── Parrot personality — cozy ──
  "¡Ya es tardecito, Heidi! Descansa 🦜",
  "El loro ya duerme… ¿y tú? 🦜",
  "¿Galleta antes de dormir, Heidi? 🦜",
  "¡A la camita, cotorrita! 🦜",
  "¡Dulces sueños, Heidi! 🦜",
  "¡Hasta mañana, lorita linda! 🦜",
  "El horno descansa, tú también 🦜",
  "Plumas en la almohada, Heidi 🦜",
  "¿Un tecito y a dormir, Heidi? 🦜",
  "Mañana volamos de nuevo 🦜",
  "¡Que sueñes con loritos, Heidi! 🦜",
  "¡Loro cansado pero feliz! 🦜",
  "Hora de volver al nido, Heidi 🦜",
  "¡Apaga la luz, lorita! 🦜",
  "Descansa, mañana hay más munchis 🦜",
  "¡Buenas noches, reina lorita! 🦜",
  "Shh… el loro ya ronca 🦜",
  "¡Mereces descansar, Heidi! 🦜",
  "Mañana con energía, hoy a dormir 🦜",
  "¡Noche, noche, cotorrita! 🦜",
  "Duerme bien, mañana horneamos más 🦜",
  "Un loro descansado vuela mejor 🦜",
  "¡Ya, Heidi! A la percha 🦜",
  "Cuida tus plumas, descansa 🦜",
  "¡El nido está calientito! 🦜",
  "Munchis te necesita fresca mañana 🦜",
  "La almohada te llama, Heidi 🦜",
  "¡Cierra los ojitos, lorita! 🦜",
  // ── Dream big while resting ──
  "Sueña en grande, Heidi 🦜",
  "El mejor negocio se hace descansada 🦜",
  "Las ideas más dulces llegan durmiendo 🦜",
  "Arianna Huffington dice: duerme bien para triunfar 🦜",
  "Tu cuerpo es tu herramienta #1, cuídalo 🦜",
  "Mañana es otro día para hacer historia 🦜",
  "Descansar no es perder el tiempo, es invertirlo 🦜",
  "Los mejores panaderos descansan bien 🦜",
  "\"Duerme lo suficiente, tus ideas lo agradecerán\" — Jeff Bezos 🦜",
  "Bill Gates duerme 7 horas… antes dormía 5 y se arrepiente 🦜",
  "LeBron duerme 10 horas… la disciplina incluye descansar 🦜",
  "\"No puedes servir de una taza vacía\" 🦜",
  "Matthew Walker: dormir es el superpoder más subestimado 🦜",
  "La creatividad necesita descanso para florecer 🦜",
  "Mañana tendrás energía para conquistar el mundo 🦜",
  "Huffington: \"el éxito no es solo logros, es bienestar\" 🦜",
  "Tu descanso de hoy es la productividad de mañana 🦜",
  "Las mejores recetas se le ocurren a la mente descansada 🦜",
  "Dormir bien es la inversión con mayor retorno 🦜",
  "Debbi Fields dormía bien para hornear mejor al día siguiente 🦜",
  // ── Tips for the night owl ──
  "Tip: deja la masa reposando toda la noche 🦜",
  "Tip: programa tus posts de mañana antes de dormir 🦜",
  "Tip: escribe 3 metas para mañana y duerme tranquila 🦜",
  "Tip: deja el workspace listo para hornear temprano 🦜",
  "Tip: revisa tu inventario de ingredientes antes de dormir 🦜",
  "Tip: piensa en tu siguiente sabor mientras sueñas 🦜",
  "Tip: anota cualquier idea antes de que se te olvide 🦜",
  "Tip: mañana empieza con lo más difícil primero 🦜",
  "Tip: revisa tus números del día con calma 🦜",
  "Tip: planifica el contenido de la semana ahora que hay calma 🦜",
];

/**
 * Returns a random greeting appropriate for the current time of day.
 * Meant to be called client-side only (uses local time).
 */
export function getGreeting(): string {
  const hour = new Date().getHours();
  const pool =
    hour < 12 ? morningGreetings : hour < 20 ? afternoonGreetings : hour < 22 ? eveningGreetings : lateNightGreetings;
  return pool[Math.floor(Math.random() * pool.length)];
}
