#!/usr/bin/env bash
set -euo pipefail

# Sets up a Conductor workspace for munchis:
#   1. Copies .env.local from master config (or .env.example)
#   2. Generates a deterministic port + container name from workspace dir name
#   3. Writes .env for docker-compose variable substitution
#
# First run:  ./scripts/setup.sh --init   (saves your .env.local as the master copy)
# New workspace: ./scripts/setup.sh        (copies master + generates unique port)

MASTER_DIR="$HOME/.config/munchis"
MASTER_ENV="$MASTER_DIR/.env.local"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOCAL_ENV="$PROJECT_DIR/.env.local"
COMPOSE_ENV="$PROJECT_DIR/.env"

# Derive workspace name from the directory name
WORKSPACE_NAME="$(basename "$PROJECT_DIR")"

# Deterministic port from workspace name (range 3001–3999)
hash_port() {
  local hash
  hash=$(printf '%s' "$1" | shasum -a 256 | cut -c1-4)
  local decimal=$((16#$hash))
  echo $(( (decimal % 999) + 3001 ))
}

HOST_PORT=$(hash_port "$WORKSPACE_NAME")

# --init: save current .env.local as the master copy
if [[ "${1:-}" == "--init" ]]; then
  if [[ ! -f "$LOCAL_ENV" ]]; then
    echo "Error: No .env.local found in project root."
    echo "Create one first (see .env.example), then run: ./scripts/setup.sh --init"
    exit 1
  fi
  mkdir -p "$MASTER_DIR"
  cp "$LOCAL_ENV" "$MASTER_ENV"
  echo "Saved master .env.local to $MASTER_ENV"
  echo "New workspaces can now run: ./scripts/setup.sh"
  exit 0
fi

# --- Step 1: .env.local (app secrets) ---
if [[ ! -f "$LOCAL_ENV" ]]; then
  if [[ -f "$MASTER_ENV" ]]; then
    cp "$MASTER_ENV" "$LOCAL_ENV"
    echo "Copied .env.local from master config."
  elif [[ -f "$PROJECT_DIR/.env.example" ]]; then
    cp "$PROJECT_DIR/.env.example" "$LOCAL_ENV"
    echo "Created .env.local from .env.example — fill in your real values."
    echo "Then run: ./scripts/setup.sh --init  (to save as master for future workspaces)"
  else
    echo "Error: No master .env.local found at $MASTER_ENV"
    echo "Run './scripts/setup.sh --init' from a workspace that has .env.local"
    exit 1
  fi
fi

# Update NEXT_PUBLIC_APP_URL to use this workspace's port
sed -i '' "s|NEXT_PUBLIC_APP_URL=.*|NEXT_PUBLIC_APP_URL=http://localhost:${HOST_PORT}|" "$LOCAL_ENV"

# --- Step 2: .env (docker-compose variables + NEXT_PUBLIC build args) ---
# Docker Compose only reads .env for YAML interpolation (${VAR}).
# NEXT_PUBLIC_* must be here so they're passed as build args to the Dockerfile
# (Next.js inlines them into JS bundles at build time).
{
  echo "# Auto-generated by setup.sh — do not edit manually"
  echo "WORKSPACE_NAME=${WORKSPACE_NAME}"
  echo "COMPOSE_PROJECT_NAME=munchis-${WORKSPACE_NAME}"
  echo "HOST_PORT=${HOST_PORT}"
  grep '^NEXT_PUBLIC_' "$LOCAL_ENV" || true
} > "$COMPOSE_ENV"

echo ""
echo "✔ Workspace ready"
echo ""
echo "  Name:      ${WORKSPACE_NAME}"
echo "  Container: munchis-web-${WORKSPACE_NAME}"
echo "  URL:       http://localhost:${HOST_PORT}"
echo ""
echo "  Production: docker compose up -d --build"
echo "  Dev:        docker compose -f docker-compose.dev.yml up -d --build"
